"""Add AI summary and confidence to findings

Revision ID: 5781e23fc763
Revises: bafebf6b45b6
Create Date: 2026-03-13 21:22:15.703320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5781e23fc763'
down_revision: Union[str, Sequence[str], None] = 'bafebf6b45b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('ai_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'ai_summary')
    # ### end Alembic commands ###
