"""Add remediation and cvss columns

Revision ID: 967f19e8684e
Revises: 5781e23fc763
Create Date: 2026-04-10 04:33:01.918230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '967f19e8684e'
down_revision: Union[str, Sequence[str], None] = '5781e23fc763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.add_column('findings', sa.Column('remediation', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('cvss_score', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('cvss_vector', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('current_phase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'current_phase')
    op.drop_column('findings', 'cvss_vector')
    op.drop_column('findings', 'cvss_score')
    op.drop_column('findings', 'remediation')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'ATTACKER', 'VIEWER', name='userrole'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
